// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.suhel.nextbell_platform

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
private object MessagesPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeAccount (
  val id: String,
  val email: String,
  val name: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeAccount {
      val id = pigeonVar_list[0] as String
      val email = pigeonVar_list[1] as String
      val name = pigeonVar_list[2] as String
      return NativeAccount(id, email, name)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      email,
      name,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeAccount
    return MessagesPigeonUtils.deepEquals(this.id, other.id) && MessagesPigeonUtils.deepEquals(this.email, other.email) && MessagesPigeonUtils.deepEquals(this.name, other.name)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.id)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.email)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.name)
    return result
  }
  override fun toString(): String {
    return "NativeAccount(id=$id, email=$email, name=$name)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeAlarm (
  val id: String,
  val entryId: String,
  val title: String,
  val subtitle: String,
  val fireAtMillis: Long,
  val snoozeMinutes: Long,
  val sourceIds: List<String>,
  val parentId: String? = null,
  val ringing: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeAlarm {
      val id = pigeonVar_list[0] as String
      val entryId = pigeonVar_list[1] as String
      val title = pigeonVar_list[2] as String
      val subtitle = pigeonVar_list[3] as String
      val fireAtMillis = pigeonVar_list[4] as Long
      val snoozeMinutes = pigeonVar_list[5] as Long
      val sourceIds = pigeonVar_list[6] as List<String>
      val parentId = pigeonVar_list[7] as String?
      val ringing = pigeonVar_list[8] as Boolean
      return NativeAlarm(id, entryId, title, subtitle, fireAtMillis, snoozeMinutes, sourceIds, parentId, ringing)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      entryId,
      title,
      subtitle,
      fireAtMillis,
      snoozeMinutes,
      sourceIds,
      parentId,
      ringing,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeAlarm
    return MessagesPigeonUtils.deepEquals(this.id, other.id) && MessagesPigeonUtils.deepEquals(this.entryId, other.entryId) && MessagesPigeonUtils.deepEquals(this.title, other.title) && MessagesPigeonUtils.deepEquals(this.subtitle, other.subtitle) && MessagesPigeonUtils.deepEquals(this.fireAtMillis, other.fireAtMillis) && MessagesPigeonUtils.deepEquals(this.snoozeMinutes, other.snoozeMinutes) && MessagesPigeonUtils.deepEquals(this.sourceIds, other.sourceIds) && MessagesPigeonUtils.deepEquals(this.parentId, other.parentId) && MessagesPigeonUtils.deepEquals(this.ringing, other.ringing)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.id)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.entryId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.title)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.subtitle)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.fireAtMillis)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.snoozeMinutes)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.sourceIds)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.parentId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.ringing)
    return result
  }
  override fun toString(): String {
    return "NativeAlarm(id=$id, entryId=$entryId, title=$title, subtitle=$subtitle, fireAtMillis=$fireAtMillis, snoozeMinutes=$snoozeMinutes, sourceIds=$sourceIds, parentId=$parentId, ringing=$ringing)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativePermissions (
  val alarms: Boolean,
  val notifications: Boolean,
  val fullScreen: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativePermissions {
      val alarms = pigeonVar_list[0] as Boolean
      val notifications = pigeonVar_list[1] as Boolean
      val fullScreen = pigeonVar_list[2] as Boolean
      return NativePermissions(alarms, notifications, fullScreen)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      alarms,
      notifications,
      fullScreen,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativePermissions
    return MessagesPigeonUtils.deepEquals(this.alarms, other.alarms) && MessagesPigeonUtils.deepEquals(this.notifications, other.notifications) && MessagesPigeonUtils.deepEquals(this.fullScreen, other.fullScreen)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.alarms)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.notifications)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.fullScreen)
    return result
  }
  override fun toString(): String {
    return "NativePermissions(alarms=$alarms, notifications=$notifications, fullScreen=$fullScreen)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeAlarmAction (
  val id: String,
  val alarmId: String,
  val kind: String,
  val atMillis: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeAlarmAction {
      val id = pigeonVar_list[0] as String
      val alarmId = pigeonVar_list[1] as String
      val kind = pigeonVar_list[2] as String
      val atMillis = pigeonVar_list[3] as Long
      return NativeAlarmAction(id, alarmId, kind, atMillis)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      alarmId,
      kind,
      atMillis,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeAlarmAction
    return MessagesPigeonUtils.deepEquals(this.id, other.id) && MessagesPigeonUtils.deepEquals(this.alarmId, other.alarmId) && MessagesPigeonUtils.deepEquals(this.kind, other.kind) && MessagesPigeonUtils.deepEquals(this.atMillis, other.atMillis)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.id)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.alarmId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.kind)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.atMillis)
    return result
  }
  override fun toString(): String {
    return "NativeAlarmAction(id=$id, alarmId=$alarmId, kind=$kind, atMillis=$atMillis)"
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeAccount.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeAlarm.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativePermissions.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeAlarmAction.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is NativeAccount -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is NativeAlarm -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is NativePermissions -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is NativeAlarmAction -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface NextbellHostApi {
  suspend fun identityToken(serverClientId: String): String
  suspend fun authorizeCloud(serverClientId: String, email: String, includeTasks: Boolean): String
  suspend fun configureCloudDevice(alarmsEnabled: Boolean, urgentNotices: Boolean)
  suspend fun connect(clientId: String, accountId: String?): NativeAccount
  suspend fun accounts(): List<NativeAccount>
  suspend fun accessToken(accountId: String): String
  suspend fun removeAccount(accountId: String)
  suspend fun permissions(): NativePermissions
  suspend fun requestPermissions(): NativePermissions
  suspend fun openSettings(section: String)
  suspend fun scheduleAlarm(alarm: NativeAlarm)
  suspend fun cancelAlarms(ids: List<String>)
  suspend fun alarms(): List<NativeAlarm>
  suspend fun pendingActions(): List<NativeAlarmAction>
  suspend fun acknowledgeActions(ids: List<String>)

  companion object {
    /** The codec used by NextbellHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `NextbellHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: NextbellHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nextbell_platform.NextbellHostApi.identityToken$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val serverClientIdArg = args[0] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.identityToken(serverClientIdArg))
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nextbell_platform.NextbellHostApi.authorizeCloud$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val serverClientIdArg = args[0] as String
            val emailArg = args[1] as String
            val includeTasksArg = args[2] as Boolean
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.authorizeCloud(serverClientIdArg, emailArg, includeTasksArg))
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nextbell_platform.NextbellHostApi.configureCloudDevice$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val alarmsEnabledArg = args[0] as Boolean
            val urgentNoticesArg = args[1] as Boolean
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.configureCloudDevice(alarmsEnabledArg, urgentNoticesArg)
                listOf(null)
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nextbell_platform.NextbellHostApi.connect$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val clientIdArg = args[0] as String
            val accountIdArg = args[1] as String?
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.connect(clientIdArg, accountIdArg))
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nextbell_platform.NextbellHostApi.accounts$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.accounts())
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nextbell_platform.NextbellHostApi.accessToken$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val accountIdArg = args[0] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.accessToken(accountIdArg))
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nextbell_platform.NextbellHostApi.removeAccount$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val accountIdArg = args[0] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.removeAccount(accountIdArg)
                listOf(null)
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nextbell_platform.NextbellHostApi.permissions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.permissions())
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nextbell_platform.NextbellHostApi.requestPermissions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.requestPermissions())
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nextbell_platform.NextbellHostApi.openSettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sectionArg = args[0] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.openSettings(sectionArg)
                listOf(null)
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nextbell_platform.NextbellHostApi.scheduleAlarm$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val alarmArg = args[0] as NativeAlarm
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.scheduleAlarm(alarmArg)
                listOf(null)
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nextbell_platform.NextbellHostApi.cancelAlarms$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idsArg = args[0] as List<String>
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.cancelAlarms(idsArg)
                listOf(null)
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nextbell_platform.NextbellHostApi.alarms$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.alarms())
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nextbell_platform.NextbellHostApi.pendingActions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.pendingActions())
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nextbell_platform.NextbellHostApi.acknowledgeActions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idsArg = args[0] as List<String>
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.acknowledgeActions(idsArg)
                listOf(null)
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
