// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

class NativeAccount {
  NativeAccount({required this.id, required this.email, required this.name});

  String id;

  String email;

  String name;

  List<Object?> _toList() {
    return <Object?>[id, email, name];
  }

  Object encode() {
    return _toList();
  }

  static NativeAccount decode(Object result) {
    result as List<Object?>;
    return NativeAccount(
      id: result[0]! as String,
      email: result[1]! as String,
      name: result[2]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeAccount || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) &&
        _deepEquals(email, other.email) &&
        _deepEquals(name, other.name);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeAccount(id: $id, email: $email, name: $name)';
  }
}

class NativeAlarm {
  NativeAlarm({
    required this.id,
    required this.entryId,
    required this.title,
    required this.subtitle,
    required this.fireAtMillis,
    required this.snoozeMinutes,
    required this.sourceIds,
    this.parentId,
    this.ringing = false,
  });

  String id;

  String entryId;

  String title;

  String subtitle;

  int fireAtMillis;

  int snoozeMinutes;

  List<String> sourceIds;

  String? parentId;

  bool ringing;

  List<Object?> _toList() {
    return <Object?>[
      id,
      entryId,
      title,
      subtitle,
      fireAtMillis,
      snoozeMinutes,
      sourceIds,
      parentId,
      ringing,
    ];
  }

  Object encode() {
    return _toList();
  }

  static NativeAlarm decode(Object result) {
    result as List<Object?>;
    return NativeAlarm(
      id: result[0]! as String,
      entryId: result[1]! as String,
      title: result[2]! as String,
      subtitle: result[3]! as String,
      fireAtMillis: result[4]! as int,
      snoozeMinutes: result[5]! as int,
      sourceIds: (result[6]! as List<Object?>).cast<String>(),
      parentId: result[7] as String?,
      ringing: result[8]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeAlarm || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) &&
        _deepEquals(entryId, other.entryId) &&
        _deepEquals(title, other.title) &&
        _deepEquals(subtitle, other.subtitle) &&
        _deepEquals(fireAtMillis, other.fireAtMillis) &&
        _deepEquals(snoozeMinutes, other.snoozeMinutes) &&
        _deepEquals(sourceIds, other.sourceIds) &&
        _deepEquals(parentId, other.parentId) &&
        _deepEquals(ringing, other.ringing);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeAlarm(id: $id, entryId: $entryId, title: $title, subtitle: $subtitle, fireAtMillis: $fireAtMillis, snoozeMinutes: $snoozeMinutes, sourceIds: $sourceIds, parentId: $parentId, ringing: $ringing)';
  }
}

class NativePermissions {
  NativePermissions({
    required this.alarms,
    required this.notifications,
    required this.fullScreen,
  });

  bool alarms;

  bool notifications;

  bool fullScreen;

  List<Object?> _toList() {
    return <Object?>[alarms, notifications, fullScreen];
  }

  Object encode() {
    return _toList();
  }

  static NativePermissions decode(Object result) {
    result as List<Object?>;
    return NativePermissions(
      alarms: result[0]! as bool,
      notifications: result[1]! as bool,
      fullScreen: result[2]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativePermissions || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(alarms, other.alarms) &&
        _deepEquals(notifications, other.notifications) &&
        _deepEquals(fullScreen, other.fullScreen);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativePermissions(alarms: $alarms, notifications: $notifications, fullScreen: $fullScreen)';
  }
}

class NativeAlarmAction {
  NativeAlarmAction({
    required this.id,
    required this.alarmId,
    required this.kind,
    required this.atMillis,
  });

  String id;

  String alarmId;

  String kind;

  int atMillis;

  List<Object?> _toList() {
    return <Object?>[id, alarmId, kind, atMillis];
  }

  Object encode() {
    return _toList();
  }

  static NativeAlarmAction decode(Object result) {
    result as List<Object?>;
    return NativeAlarmAction(
      id: result[0]! as String,
      alarmId: result[1]! as String,
      kind: result[2]! as String,
      atMillis: result[3]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeAlarmAction || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) &&
        _deepEquals(alarmId, other.alarmId) &&
        _deepEquals(kind, other.kind) &&
        _deepEquals(atMillis, other.atMillis);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeAlarmAction(id: $id, alarmId: $alarmId, kind: $kind, atMillis: $atMillis)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is NativeAccount) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is NativeAlarm) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is NativePermissions) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is NativeAlarmAction) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return NativeAccount.decode(readValue(buffer)!);
      case 130:
        return NativeAlarm.decode(readValue(buffer)!);
      case 131:
        return NativePermissions.decode(readValue(buffer)!);
      case 132:
        return NativeAlarmAction.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class NextbellHostApi {
  /// Constructor for [NextbellHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  NextbellHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<NativeAccount> connect(String clientId, String? accountId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.nextbell_platform.NextbellHostApi.connect$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[clientId, accountId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as NativeAccount;
  }

  Future<List<NativeAccount>> accounts() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.nextbell_platform.NextbellHostApi.accounts$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>).cast<NativeAccount>();
  }

  Future<String> accessToken(String accountId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.nextbell_platform.NextbellHostApi.accessToken$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[accountId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as String;
  }

  Future<void> removeAccount(String accountId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.nextbell_platform.NextbellHostApi.removeAccount$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[accountId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<NativePermissions> permissions() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.nextbell_platform.NextbellHostApi.permissions$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as NativePermissions;
  }

  Future<NativePermissions> requestPermissions() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.nextbell_platform.NextbellHostApi.requestPermissions$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as NativePermissions;
  }

  Future<void> openSettings(String section) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.nextbell_platform.NextbellHostApi.openSettings$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[section],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> scheduleAlarm(NativeAlarm alarm) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.nextbell_platform.NextbellHostApi.scheduleAlarm$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[alarm],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> cancelAlarms(List<String> ids) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.nextbell_platform.NextbellHostApi.cancelAlarms$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[ids],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<List<NativeAlarm>> alarms() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.nextbell_platform.NextbellHostApi.alarms$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>).cast<NativeAlarm>();
  }

  Future<List<NativeAlarmAction>> pendingActions() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.nextbell_platform.NextbellHostApi.pendingActions$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>).cast<NativeAlarmAction>();
  }

  Future<void> acknowledgeActions(List<String> ids) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.nextbell_platform.NextbellHostApi.acknowledgeActions$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[ids],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }
}
