// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Generated class from Pigeon that represents data sent in messages.
struct NativeAccount: Hashable, CustomStringConvertible {
  var id: String
  var email: String
  var name: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeAccount? {
    let id = pigeonVar_list[0] as! String
    let email = pigeonVar_list[1] as! String
    let name = pigeonVar_list[2] as! String

    return NativeAccount(
      id: id,
      email: email,
      name: name
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      email,
      name,
    ]
  }
  static func == (lhs: NativeAccount, rhs: NativeAccount) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.id, rhs.id) && MessagesPigeonInternal.deepEquals(lhs.email, rhs.email) && MessagesPigeonInternal.deepEquals(lhs.name, rhs.name)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeAccount")
    MessagesPigeonInternal.deepHash(value: id, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: email, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: name, hasher: &hasher)
  }

  public var description: String {
    return "NativeAccount(id: \(String(describing: id)), email: \(String(describing: email)), name: \(String(describing: name)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeAlarm: Hashable, CustomStringConvertible {
  var id: String
  var entryId: String
  var title: String
  var subtitle: String
  var fireAtMillis: Int64
  var snoozeMinutes: Int64
  var sourceIds: [String]
  var parentId: String? = nil
  var ringing: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeAlarm? {
    let id = pigeonVar_list[0] as! String
    let entryId = pigeonVar_list[1] as! String
    let title = pigeonVar_list[2] as! String
    let subtitle = pigeonVar_list[3] as! String
    let fireAtMillis = pigeonVar_list[4] as! Int64
    let snoozeMinutes = pigeonVar_list[5] as! Int64
    let sourceIds = pigeonVar_list[6] as! [String]
    let parentId: String? = nilOrValue(pigeonVar_list[7])
    let ringing = pigeonVar_list[8] as! Bool

    return NativeAlarm(
      id: id,
      entryId: entryId,
      title: title,
      subtitle: subtitle,
      fireAtMillis: fireAtMillis,
      snoozeMinutes: snoozeMinutes,
      sourceIds: sourceIds,
      parentId: parentId,
      ringing: ringing
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      entryId,
      title,
      subtitle,
      fireAtMillis,
      snoozeMinutes,
      sourceIds,
      parentId,
      ringing,
    ]
  }
  static func == (lhs: NativeAlarm, rhs: NativeAlarm) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.id, rhs.id) && MessagesPigeonInternal.deepEquals(lhs.entryId, rhs.entryId) && MessagesPigeonInternal.deepEquals(lhs.title, rhs.title) && MessagesPigeonInternal.deepEquals(lhs.subtitle, rhs.subtitle) && MessagesPigeonInternal.deepEquals(lhs.fireAtMillis, rhs.fireAtMillis) && MessagesPigeonInternal.deepEquals(lhs.snoozeMinutes, rhs.snoozeMinutes) && MessagesPigeonInternal.deepEquals(lhs.sourceIds, rhs.sourceIds) && MessagesPigeonInternal.deepEquals(lhs.parentId, rhs.parentId) && MessagesPigeonInternal.deepEquals(lhs.ringing, rhs.ringing)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeAlarm")
    MessagesPigeonInternal.deepHash(value: id, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: entryId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: title, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: subtitle, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: fireAtMillis, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: snoozeMinutes, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: sourceIds, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: parentId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: ringing, hasher: &hasher)
  }

  public var description: String {
    return "NativeAlarm(id: \(String(describing: id)), entryId: \(String(describing: entryId)), title: \(String(describing: title)), subtitle: \(String(describing: subtitle)), fireAtMillis: \(String(describing: fireAtMillis)), snoozeMinutes: \(String(describing: snoozeMinutes)), sourceIds: \(String(describing: sourceIds)), parentId: \(String(describing: parentId)), ringing: \(String(describing: ringing)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativePermissions: Hashable, CustomStringConvertible {
  var alarms: Bool
  var notifications: Bool
  var fullScreen: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativePermissions? {
    let alarms = pigeonVar_list[0] as! Bool
    let notifications = pigeonVar_list[1] as! Bool
    let fullScreen = pigeonVar_list[2] as! Bool

    return NativePermissions(
      alarms: alarms,
      notifications: notifications,
      fullScreen: fullScreen
    )
  }
  func toList() -> [Any?] {
    return [
      alarms,
      notifications,
      fullScreen,
    ]
  }
  static func == (lhs: NativePermissions, rhs: NativePermissions) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.alarms, rhs.alarms) && MessagesPigeonInternal.deepEquals(lhs.notifications, rhs.notifications) && MessagesPigeonInternal.deepEquals(lhs.fullScreen, rhs.fullScreen)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativePermissions")
    MessagesPigeonInternal.deepHash(value: alarms, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: notifications, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: fullScreen, hasher: &hasher)
  }

  public var description: String {
    return "NativePermissions(alarms: \(String(describing: alarms)), notifications: \(String(describing: notifications)), fullScreen: \(String(describing: fullScreen)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeAlarmAction: Hashable, CustomStringConvertible {
  var id: String
  var alarmId: String
  var kind: String
  var atMillis: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeAlarmAction? {
    let id = pigeonVar_list[0] as! String
    let alarmId = pigeonVar_list[1] as! String
    let kind = pigeonVar_list[2] as! String
    let atMillis = pigeonVar_list[3] as! Int64

    return NativeAlarmAction(
      id: id,
      alarmId: alarmId,
      kind: kind,
      atMillis: atMillis
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      alarmId,
      kind,
      atMillis,
    ]
  }
  static func == (lhs: NativeAlarmAction, rhs: NativeAlarmAction) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.id, rhs.id) && MessagesPigeonInternal.deepEquals(lhs.alarmId, rhs.alarmId) && MessagesPigeonInternal.deepEquals(lhs.kind, rhs.kind) && MessagesPigeonInternal.deepEquals(lhs.atMillis, rhs.atMillis)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeAlarmAction")
    MessagesPigeonInternal.deepHash(value: id, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: alarmId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: kind, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: atMillis, hasher: &hasher)
  }

  public var description: String {
    return "NativeAlarmAction(id: \(String(describing: id)), alarmId: \(String(describing: alarmId)), kind: \(String(describing: kind)), atMillis: \(String(describing: atMillis)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return NativeAccount.fromList(self.readValue() as! [Any?])
    case 130:
      return NativeAlarm.fromList(self.readValue() as! [Any?])
    case 131:
      return NativePermissions.fromList(self.readValue() as! [Any?])
    case 132:
      return NativeAlarmAction.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? NativeAccount {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? NativeAlarm {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? NativePermissions {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? NativeAlarmAction {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol NextbellHostApi {
  func identityToken(serverClientId: String) async throws -> String
  func authorizeCloud(serverClientId: String, email: String, includeTasks: Bool) async throws -> String
  func configureCloudDevice(alarmsEnabled: Bool, urgentNotices: Bool) async throws
  func connect(clientId: String, accountId: String?) async throws -> NativeAccount
  func accounts() async throws -> [NativeAccount]
  func accessToken(accountId: String) async throws -> String
  func removeAccount(accountId: String) async throws
  func permissions() async throws -> NativePermissions
  func requestPermissions() async throws -> NativePermissions
  func openSettings(section: String) async throws
  func scheduleAlarm(alarm: NativeAlarm) async throws
  func cancelAlarms(ids: [String]) async throws
  func alarms() async throws -> [NativeAlarm]
  func pendingActions() async throws -> [NativeAlarmAction]
  func acknowledgeActions(ids: [String]) async throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class NextbellHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `NextbellHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: NextbellHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let identityTokenChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nextbell_platform.NextbellHostApi.identityToken\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      identityTokenChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let serverClientIdArg = args[0] as! String
        Task { @MainActor in
          do {
            let result = try await api.identityToken(serverClientId: serverClientIdArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      identityTokenChannel.setMessageHandler(nil)
    }
    let authorizeCloudChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nextbell_platform.NextbellHostApi.authorizeCloud\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      authorizeCloudChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let serverClientIdArg = args[0] as! String
        let emailArg = args[1] as! String
        let includeTasksArg = args[2] as! Bool
        Task { @MainActor in
          do {
            let result = try await api.authorizeCloud(serverClientId: serverClientIdArg, email: emailArg, includeTasks: includeTasksArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      authorizeCloudChannel.setMessageHandler(nil)
    }
    let configureCloudDeviceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nextbell_platform.NextbellHostApi.configureCloudDevice\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      configureCloudDeviceChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let alarmsEnabledArg = args[0] as! Bool
        let urgentNoticesArg = args[1] as! Bool
        Task { @MainActor in
          do {
            try await api.configureCloudDevice(alarmsEnabled: alarmsEnabledArg, urgentNotices: urgentNoticesArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      configureCloudDeviceChannel.setMessageHandler(nil)
    }
    let connectChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nextbell_platform.NextbellHostApi.connect\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      connectChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let clientIdArg = args[0] as! String
        let accountIdArg: String? = nilOrValue(args[1])
        Task { @MainActor in
          do {
            let result = try await api.connect(clientId: clientIdArg, accountId: accountIdArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      connectChannel.setMessageHandler(nil)
    }
    let accountsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nextbell_platform.NextbellHostApi.accounts\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      accountsChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            let result = try await api.accounts()
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      accountsChannel.setMessageHandler(nil)
    }
    let accessTokenChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nextbell_platform.NextbellHostApi.accessToken\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      accessTokenChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let accountIdArg = args[0] as! String
        Task { @MainActor in
          do {
            let result = try await api.accessToken(accountId: accountIdArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      accessTokenChannel.setMessageHandler(nil)
    }
    let removeAccountChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nextbell_platform.NextbellHostApi.removeAccount\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      removeAccountChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let accountIdArg = args[0] as! String
        Task { @MainActor in
          do {
            try await api.removeAccount(accountId: accountIdArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      removeAccountChannel.setMessageHandler(nil)
    }
    let permissionsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nextbell_platform.NextbellHostApi.permissions\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      permissionsChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            let result = try await api.permissions()
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      permissionsChannel.setMessageHandler(nil)
    }
    let requestPermissionsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nextbell_platform.NextbellHostApi.requestPermissions\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestPermissionsChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            let result = try await api.requestPermissions()
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestPermissionsChannel.setMessageHandler(nil)
    }
    let openSettingsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nextbell_platform.NextbellHostApi.openSettings\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openSettingsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sectionArg = args[0] as! String
        Task { @MainActor in
          do {
            try await api.openSettings(section: sectionArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      openSettingsChannel.setMessageHandler(nil)
    }
    let scheduleAlarmChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nextbell_platform.NextbellHostApi.scheduleAlarm\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      scheduleAlarmChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let alarmArg = args[0] as! NativeAlarm
        Task { @MainActor in
          do {
            try await api.scheduleAlarm(alarm: alarmArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      scheduleAlarmChannel.setMessageHandler(nil)
    }
    let cancelAlarmsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nextbell_platform.NextbellHostApi.cancelAlarms\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelAlarmsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idsArg = args[0] as! [String]
        Task { @MainActor in
          do {
            try await api.cancelAlarms(ids: idsArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      cancelAlarmsChannel.setMessageHandler(nil)
    }
    let alarmsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nextbell_platform.NextbellHostApi.alarms\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      alarmsChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            let result = try await api.alarms()
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      alarmsChannel.setMessageHandler(nil)
    }
    let pendingActionsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nextbell_platform.NextbellHostApi.pendingActions\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pendingActionsChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            let result = try await api.pendingActions()
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      pendingActionsChannel.setMessageHandler(nil)
    }
    let acknowledgeActionsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nextbell_platform.NextbellHostApi.acknowledgeActions\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      acknowledgeActionsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idsArg = args[0] as! [String]
        Task { @MainActor in
          do {
            try await api.acknowledgeActions(ids: idsArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      acknowledgeActionsChannel.setMessageHandler(nil)
    }
  }
}
